[package]
name = "understand-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
csv = "1.3.0"
itertools = "0.12.1"
serde = { version = "1.0.202", features = ["derive"] }
strum = { version = "0.26.2", features = ["strum_macros"] }
strum_macros = "0.26.4"
